[package]
name = "relayer-modules"
version = "0.1.0"
edition = "2018"
authors = [
  "Anca Zamfir <anca@interchain.io>",
  "Romain Ruetschi <romain@informal.systems>"
]

[features]
# Default features
#default = ["paths-cosmos"]
default = ["paths-ics"]

# In IBC queries, use paths as defined in the Cosmos-SDK Go implementation, rather than in the ICS.
paths-cosmos = []
paths-ics = []

[dependencies]
tendermint = { git = "https://github.com/informalsystems/tendermint-rs.git", branch = "master" }

anomaly = "0.2.0"
thiserror = "1.0"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }

