[package]
name       = "ibc-proto"
version    = "0.11.0"
authors    = ["Informal Systems <hello@informal.systems>"]
edition    = "2018"
license    = "Apache-2.0"
repository = "https://github.com/informalsystems/ibc-rs/tree/master/proto"
readme     = "README.md"
categories = ["cryptography", "cryptography::cryptocurrencies", "database"]
keywords   = ["blockchain", "cosmos", "tendermint", "ibc", "proto"]
exclude    = ["definitions"]

description = """
    ibc-proto is a Rust implementation of the Cosmos SDK & IBC proto structs.
    """

[lib]
name = "ibc_proto"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost = "0.7"
prost-types = "0.7"
bytes = "1.1"
tonic = { version = "0.4", optional = true }

[dependencies.tendermint-proto]
version = "=0.22.0"

[features]
default = ["std"]
std = ["tonic"]
