[package]
name = "no-std-check"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]

ibc = { path = "../../modules", optional = true, default-features = false }
ibc-proto = { path = "../../proto", optional = true, default-features = false }
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std", optional = true, default-features = false }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std", optional = true, default-features = false }

sp-core = { version = "3.0.0", default-features = false, optional = true }
sp-io = { version = "3.0.0", default-features = false, optional = true }
sp-runtime = { version = "3.0.0", default-features = false, optional = true }
sp-std = { version = "3.0.0", default-features = false, optional = true }

prost = { version = "0.7", default-features = false }
prost-types = { version = "0.7", default-features = false }
bytes = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_bytes = { version = "0.11", default-features = false, features = ["alloc"] }
subtle-encoding = { version = "0.5", default-features = false, features = ["hex", "base64", "bech32-preview"] }
num-traits = { version = "0.2", default-features = false }
num-derive = { version = "0.3", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["serde", "alloc"] }
flex-error = { version = "0.4.3", default-features = false }

async-trait = { version = "0.1", default-features = false }
ed25519 = { version = "1", default-features = false }
ed25519-dalek = { version = "1", default-features = false, features = ["u64_backend"] }
futures = { version = "0.3", default-features = false }
once_cell = { version = "1.3", default-features = false }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
serde_repr = { version = "0.1", default-features = false }
sha2 = { version = "0.9", default-features = false }
signature = { version = "1.2", default-features = false }
subtle = { version = "2", default-features = false }
zeroize = { version = "1.1", default-features = false, features = ["zeroize_derive", "alloc"] }
k256 = { version = "0.9", default-features = false , features = ["ecdsa", "sha256"] }
ripemd160 = { version = "0.9", default-features = false }
# ics23 = { version = "0.6.5", default-features = false }
tracing = { version = "0.1.28", default-features = false }
serde_derive = { version = "1.0.104", default-features = false }
safe-regex = { version = "0.2.4" }

[features]
default = []
use-ibc = [
  # "ibc",
  # "ibc-proto",
  # "tendermint",
  # "tendermint-proto",
]
use-substrate = [
  "sp-core",
  "sp-io",
  "sp-runtime",
  "sp-std",
]

use-unsupported = [
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "soares/activate-no-std" }
# ics23 = { git = "https://github.com/confio/ics23.git", branch = "master" }
safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", branch = "main" }
